### ISSUE TITLE
login and logout

### ISSUE THREAD

**Issue by baudoliver7** [minlessika/my-supervisor#32]
When user is logged in, he must show home page of supervisor.

**Comment by 0pdd** [comment]
@baudoliver7 the puzzle [#41](https://github.com/my-supervisor/my-supervisor/issues/41) is still not solved.

**Comment by 0pdd** [comment]
@baudoliver7 the only puzzle [#41](https://github.com/my-supervisor/my-supervisor/issues/41) is solved here.
